server:
  servlet:
    context-path: "/api/v1"
  port: 8090

jwt:
  auth:
    converter:
      principal-claim-name: preferred_username
      resource-id: spring-3d-scan-api

spring:
  security:
    oauth2: 
      resourceserver:
        jwt:
          issuer-uri: "issuer-uri"
          jwk-set-uri: "jwk-set-uri"
  application:
    name: scan3d

  datasource:
    url: "jdbc:postgresql://localhost:5433/scan3d-db"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: scan_3d

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: scan_3d

  flyway:
    enabled: true
    default-schema: scan_3d
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    fail-on-missing-locations: true
    placeholders:
      schema: 'scan_3d'

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: INFO
